import { v4 as uuidv4 } from 'uuid';
import { ButtonControl } from 'mainWindow/components/MidiButton';
import { EncoderControl } from 'mainWindow/components/MidiEncoder';
import { FaderControl } from 'mainWindow/components/MidiFader';
import { ToggleButtonControl } from 'mainWindow/components/MidiToggleButton';

export interface ControllerDefinition {
  name: string;
  type: 'MCU' | 'FP';
  width: number;
  deviceName: {
    macOS: string;
    windows: string;
  };
  controls: Array<ButtonControl | FaderControl | ToggleButtonControl | EncoderControl>;
}

export const PresonusFaderPort: ControllerDefinition = {
  name: 'Presonus FaderPort8',
  type: 'MCU',
  width: 100,
  deviceName: {
    macOS: '',
    windows: '',
  },
  controls: [{
    uuid: uuidv4(),
    label: 'Encoder',
    type: 'Encoder',
    size: 'small',
    position: {
      x: 4,
      y: 6,
    },
    midi: [0xb0, 0x10, 0x7f],
    click: [0x90, 0x20, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'Arm',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 12,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x00, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'UnSolo',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x01, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'UnMute',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x02, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'Bypass',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 28,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x03, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'Macro',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 32,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x04, 0x7f],
  },{
    uuid: uuidv4(),
    label: 'Link',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 36,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x05, 0x7f],
  },
  /**
     * Left Shift
     */
  {
    uuid: uuidv4(),
    label: 'Shift',
    type: 'Button',
    size: 'default',
    position: {
      x: 4,
      y: 42,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x06, 0x7f],
  },
  // Select Buttons
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 12,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x18, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 20,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x19, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 28,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1a, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 36,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1b, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 44,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1c, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 52,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1d, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 60,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1e, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Select',
    type: 'Button',
    size: 'default',
    position: {
      x: 68,
      y: 12,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x1f, 0x7f],
  },
  // Solo buttons
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 12,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x08, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 20,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x09, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 28,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0a, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 36,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0b, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 44,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0c, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 52,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0d, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 60,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0e, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Solo',
    type: 'Button',
    size: 'default',
    position: {
      x: 68,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x0f, 0x7f],
  },
  // Mute buttons
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 12,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x10, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 20,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x11, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 28,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x12, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 36,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x13, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 44,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x14, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 52,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x15, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 60,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x16, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Mute',
    type: 'Button',
    size: 'default',
    position: {
      x: 68,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x17, 0x7f],
  },
  // The Track Faders
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 12,
      y: 28,
      height: 28,
    },
    midi: [0xe0, 0x7f, 0x7f],
    touch: [0x90, 0x68, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 20,
      y: 28,
      height: 28,
    },
    midi: [0xe1, 0x7f, 0x7f],
    touch: [0x90, 0x69, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 28,
      y: 28,
      height: 28,
    },
    midi: [0xe2, 0x7f, 0x7f],
    touch: [0x90, 0x6a, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 36,
      y: 28,
      height: 28,
    },
    midi: [0xe3, 0x7f, 0x7f],
    touch: [0x90, 0x6b, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 44,
      y: 28,
      height: 28,
    },
    midi: [0xe4, 0x7f, 0x7f],
    touch: [0x90, 0x6c, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 52,
      y: 28,
      height: 28,
    },
    midi: [0xe5, 0x7f, 0x7f],
    touch: [0x90, 0x6d, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 60,
      y: 28,
      height: 28,
    },
    midi: [0xe6, 0x7f, 0x7f],
    touch: [0x90, 0x6e, 0x7f],
  },
  {
    uuid: uuidv4(),
    type: 'Fader',
    position: {
      x: 68,
      y: 28,
      height: 28,
    },
    midi: [0xe7, 0x7f, 0x7f],
    touch: [0x90, 0x6f, 0x7f],
  },
  /** 
   * Fader Mode Buttons
   */
  {
    uuid: uuidv4(),
    label: 'Track',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 8,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x28, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Edit Pl',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 12,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x2b, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Sends',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 16,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x29, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Pan',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 20,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x2a, 0x7f],
  },
  /**
   * Mix Management Buttons
   */
  {
    uuid: uuidv4(),
    label: 'Audio',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 28,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x08, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'VI',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 32,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x09, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Bus',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 36,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x0a, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'VCA',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 40,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x0b, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'All',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 44,
    },
    hasRGB: true,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x0b, 0x7f],
  },
  /**
   * Shift right
   */
  {
    uuid: uuidv4(),
    label: 'Shift',
    type: 'Button',
    size: 'default',
    position: {
      x: 76,
      y: 48,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x46, 0x7f],
  },
  /**
   * Automation buttons
   */
  // The first row
  {
    uuid: uuidv4(),
    label: 'Latch',
    type: 'Button',
    size: 'default',
    position: {
      x: 84,
      y: 16,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x03, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Trim',
    type: 'Button',
    size: 'default',
    position: {
      x: 91,
      y: 16,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x4d, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Off',
    type: 'Button',
    size: 'default',
    position: {
      x: 98,
      y: 16,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x4b, 0x7f],
  },
  // The second row
  {
    uuid: uuidv4(),
    label: 'Touch',
    type: 'Button',
    size: 'default',
    position: {
      x: 84,
      y: 20,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x03, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Write',
    type: 'Button',
    size: 'default',
    position: {
      x: 91,
      y: 20,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x4d, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Read',
    type: 'Button',
    size: 'default',
    position: {
      x: 98,
      y: 20,
    },
    hasRGB: true,
    hasFeedback: true,
    midi: [0x90, 0x4b, 0x7f],
  },
  // Encoder and prev/next
  {
    uuid: uuidv4(),
    label: 'Prev',
    type: 'Button',
    size: 'default',
    position: {
      x: 84,
      y: 26,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x2e, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Encoder',
    type: 'Encoder',
    size: 'default',
    position: {
      x: 91,
      y: 26,
    },
    midi: [0xb0, 0x10, 0x7f],
    click: [0x90, 0x20, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Next',
    type: 'Button',
    size: 'default',
    position: {
      x: 98,
      y: 26,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x2f, 0x7f],
  },
  /**
   * Session Navigation
   */
  // The first row
  {
    uuid: uuidv4(),
    label: 'Channel',
    type: 'Button',
    size: 'default',
    position: {
      x: 82,
      y: 32,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x05, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Zoom',
    type: 'Button',
    size: 'default',
    position: {
      x: 88,
      y: 32,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x2a, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Scroll',
    type: 'Button',
    size: 'default',
    position: {
      x: 94,
      y: 32,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x36, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Bank',
    type: 'Button',
    size: 'default',
    position: {
      x: 100,
      y: 32,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffffff',
    midi: [0x90, 0x38, 0x7f],
  },
  // The second row
  {
    uuid: uuidv4(),
    label: 'Master',
    type: 'Button',
    size: 'default',
    position: {
      x: 82,
      y: 36,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x3a, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Click',
    type: 'Button',
    size: 'default',
    position: {
      x: 88,
      y: 36,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x3b, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Section',
    type: 'Button',
    size: 'default',
    position: {
      x: 94,
      y: 36,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#00ff00',
    midi: [0x90, 0x3c, 0x7f],
  }, {
    uuid: uuidv4(),
    label: 'Marker',
    type: 'Button',
    size: 'default',
    position: {
      x: 100,
      y: 36,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#00ff00',
    midi: [0x90, 0x3d, 0x7f],
  },
  // Transport
  {
    uuid: uuidv4(),
    label: 'Stop',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 84,
      y: 46,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ffff00',
    midi: [0x90, 0x5d, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Cycle',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 86,
      y: 42,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#0000ff',
    midi: [0x90, 0x56, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Rewind',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 91,
      y: 42,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#00ff00',
    midi: [0x90, 0x5b, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Forward',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 96,
      y: 42,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#00ff00',
    midi: [0x90, 0x5c, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Record',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 98,
      y: 46,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#ff0000',
    midi: [0x90, 0x5f, 0x7f],
  },
  {
    uuid: uuidv4(),
    label: 'Play',
    type: 'RoundButton',
    size: 'default',
    position: {
      x: 91,
      y: 47,
    },
    hasRGB: false,
    hasFeedback: true,
    color: '#00ff00',
    midi: [0x90, 0x5e, 0x7f],
  },
  ],
};
